apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: complete-devops-project
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cloudlumanex/Complete-DevOps-Project.git
    targetRevision: HEAD
    path: terraform-configs/complete-devops-project-time-printer

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
